### ISSUE TITLE
Using with GFX

### ISSUE THREAD

**Issue by jeanetteclark** [yinkou/Arduboy-TinyFont#5]
Sorry for the beginner question - but is it possible to use this font with the adafruit GFX library? It looks like it should be possible but I cannot figure out how to implement it.

**Comment by BotiKis** [comment]
Hi Jeanette!

I am not familiar with the adafruit GFX lib, but by skimming over the code on github it should be possible.
TinyFont was created with an 1 bit display buffer for the Arduboy in mind. The arduboy library took a lot from the GFX lib.
You probably want to use an instance of `GFXcanvas1` and use `getBuffer()` in the constructor of `TinyFont`.
If you need colours then you will need to rework the `printChar()` and `drawByte()` methods since it's only designed for 1 bit colour.

Hope that helps and good luck!
